# GolfMotorCompany 9.1

***`Task 1: Import Pandas Library and create a dataframe named “tyresales” from a given URL and then print it. `***
URL - https://raw.githubusercontent.com/Invact-Abhay/DO9/main/tyresale.csv

In [1]:
import pandas as pd
tyresales=pd.read_csv("https://raw.githubusercontent.com/Invact-Abhay/DO9/main/tyresale.csv")
tyresales

,OrderID,ProductName,ProductCategory,CustomerName,CustomerCategory,Month,Zone,UnitsSold,PerUnitPrice,SalesCommissionPaid
0,1,Car Tyres Rapid,Car,@alpha motors pvt ltd,Big,January,East,77,131.22,532.59
1,2,Car Tyres Rapid,Car,@ alpha motors pvt ltd,Big,January,South,16,131.37,121.74
2,3,Car Tyres Rapid,Car,@ alpha motors pvt ltd,Big,January,West,35,197.60,384.94
3,4,Car Tyres Rapid,Car,@BRAVO AUTO CORP,Medium,January,East,74,111.72,437.32
4,5,Car Tyres Rapid,Car,@ BRAVO AUTO CORP,Medium,January,Central,30,191.15,307.06
...,...,...,...,...,...,...,...,...,...,...
1431,1432,Two-wheeler Tyres Cruiser,Two-wheeler,@ INDIA TYRES CO,Medium,June,Central,50,96.53,266.44
1432,1433,Two-wheeler Tyres Cruiser,Two-wheeler,@ india tyres co,Medium,June,North,41,145.93,334.47
1433,1434,Two-wheeler Tyres Cruiser,Two-wheeler,@juliet automotive pvt ltd,Small,June,North,18,82.01,80.93
1434,1435,Two-wheeler Tyres Cruiser,Two-wheeler,@ JULIET AUTOMOTIVE PVT LTD,Small,June,Central,75,83.58,363.91
1435,1436,Two-wheeler Tyres Cruiser,Two-wheeler,@JULIET AUTOMOTIVE PVT LTD,Small,June,East,39,121.33,255.87

***`Task 2: Clean the customer name by using strip and title function and removing '@' and any space between the name and give name to this column - ‘CustomerNameClean’ then retrieve ‘CustomerNameClean’ in Alphabetical order. ‘CustomerNameClean’ should look like this - AlphaMotorsPvtLtd.`***

In [2]:
tyresales["CustomerNameClean"]=tyresales["CustomerName"].str.strip().str.title().str.replace('@','').str.replace(' ','')
tyresales.sort_values('CustomerNameClean',ascending=True)["CustomerNameClean"]
tyresales

,OrderID,ProductName,ProductCategory,CustomerName,CustomerCategory,Month,Zone,UnitsSold,PerUnitPrice,SalesCommissionPaid,CustomerNameClean
0,1,Car Tyres Rapid,Car,@alpha motors pvt ltd,Big,January,East,77,131.22,532.59,AlphaMotorsPvtLtd
1,2,Car Tyres Rapid,Car,@ alpha motors pvt ltd,Big,January,South,16,131.37,121.74,AlphaMotorsPvtLtd
2,3,Car Tyres Rapid,Car,@ alpha motors pvt ltd,Big,January,West,35,197.60,384.94,AlphaMotorsPvtLtd
3,4,Car Tyres Rapid,Car,@BRAVO AUTO CORP,Medium,January,East,74,111.72,437.32,BravoAutoCorp
4,5,Car Tyres Rapid,Car,@ BRAVO AUTO CORP,Medium,January,Central,30,191.15,307.06,BravoAutoCorp
...,...,...,...,...,...,...,...,...,...,...,...
1431,1432,Two-wheeler Tyres Cruiser,Two-wheeler,@ INDIA TYRES CO,Medium,June,Central,50,96.53,266.44,IndiaTyresCo
1432,1433,Two-wheeler Tyres Cruiser,Two-wheeler,@ india tyres co,Medium,June,North,41,145.93,334.47,IndiaTyresCo
1433,1434,Two-wheeler Tyres Cruiser,Two-wheeler,@juliet automotive pvt ltd,Small,June,North,18,82.01,80.93,JulietAutomotivePvtLtd
1434,1435,Two-wheeler Tyres Cruiser,Two-wheeler,@ JULIET AUTOMOTIVE PVT LTD,Small,June,Central,75,83.58,363.91,JulietAutomotivePvtLtd
1435,1436,Two-wheeler Tyres Cruiser,Two-wheeler,@JULIET AUTOMOTIVE PVT LTD,Small,June,East,39,121.33,255.87,JulietAutomotivePvtLtd

***`Task 3: Calculate the Sales for every customer by calculating Sales column.`***

In [3]:
sales_for_customers=tyresales.groupby('CustomerNameClean')["SalesCommissionPaid"].sum()
sales_for_customers

CustomerNameClean
AlphaMotorsPvtLtd         77946.56
BravoAutoCorp             70471.01
CharlieTransportLtd       81306.94
DeltaVehiclesPvtLtd       67603.12
EchoMotorsLtd             88613.13
FoxtrotAutoLtd            70626.97
GolfMotorCompany          78859.63
HotelWheelsInc            71807.04
IndiaTyresCo              85925.05
JulietAutomotivePvtLtd    66133.90
Name: SalesCommissionPaid, dtype: float64

***`Task 4: Find the total Sales.`***

In [4]:
total_sales=tyresales["SalesCommissionPaid"].sum()
total_sales

759293.3500000001

***`Task 5: Take the user Input for CustomerNameClean and retrieve the data for 'Alpha Motors Pvt Ltd'.`***

In [5]:
import pandas as pd
import re
# Define a function to split at title-case words and rejoin them without commas
def split_title_words(name):
    # Split based on title-case words
    words = re.findall(r'[A-Z][a-z]*', name)
    # Rejoin the words without commas, using space as a separator
    return ' '.join(words)

# Apply the function to the CustomerName column
tyresales['CustomerNameSplit'] = tyresales['CustomerNameClean'].apply(split_title_words)

#print(tyresales)
#tyresales[['CustomerNameSplit','CustomerNameClean']]
# Take user input for CustomerNameClean
customer_input = input("Enter the Customer Name (e.g., AlphaMotorsPvtLtd): ")

# Retrieve data for the inputted customer name
retrieve_data = tyresales.query('CustomerNameClean== @customer_input')

# Check if the customer exists in the data and print the result
if not retrieve_data.empty:
    print(retrieve_data)
else:
    print(f"No data found for customer: {customer_input}")

Enter the Customer Name (e.g., AlphaMotorsPvtLtd): AlphaMotorsPvtLtd
      OrderID                ProductName ProductCategory  \
0           1            Car Tyres Rapid             Car
1           2            Car Tyres Rapid             Car
2           3            Car Tyres Rapid             Car
35         36          Car Tyres Gripper             Car
36         37          Car Tyres Gripper             Car
...       ...                        ...             ...
1379     1380    Two-wheeler Tyres Swift     Two-wheeler
1409     1410  Two-wheeler Tyres Cruiser     Two-wheeler
1410     1411  Two-wheeler Tyres Cruiser     Two-wheeler
1411     1412  Two-wheeler Tyres Cruiser     Two-wheeler
1412     1413  Two-wheeler Tyres Cruiser     Two-wheeler

                  CustomerName CustomerCategory    Month     Zone  UnitsSold  \
0       @alpha motors pvt ltd               Big  January     East         77
1       @ alpha motors pvt ltd              Big  January    South         16
2       @ alpha motors pvt ltd              Big  January     West         35
35      @ alpha motors pvt ltd              Big  January     East         20
36      @ALPHA MOTORS PVT LTD               Big  January    North         73
...                        ...              ...      ...      ...        ...
1379    @ alpha motors pvt ltd              Big     June     East         33
1409    @ALPHA MOTORS PVT LTD               Big     June     East         72
1410   @ alpha motors pvt ltd               Big     June  Central         69
1411     @Alpha Motors Pvt Ltd              Big     June    South         36
1412   @ alpha motors pvt ltd               Big     June     East         84

      PerUnitPrice  SalesCommissionPaid  CustomerNameClean  \
0           131.22               532.59  AlphaMotorsPvtLtd
1           131.37               121.74  AlphaMotorsPvtLtd
2           197.60               384.94  AlphaMotorsPvtLtd
35          149.00               161.06  AlphaMotorsPvtLtd
36          189.78               819.87  AlphaMotorsPvtLtd
...            ...                  ...                ...
1379        125.42               228.35  AlphaMotorsPvtLtd
1409        129.81               477.22  AlphaMotorsPvtLtd
1410        124.01               437.55  AlphaMotorsPvtLtd
1411        147.49               273.22  AlphaMotorsPvtLtd
1412         90.73               429.31  AlphaMotorsPvtLtd

         CustomerNameSplit
0     Alpha Motors Pvt Ltd
1     Alpha Motors Pvt Ltd
2     Alpha Motors Pvt Ltd
35    Alpha Motors Pvt Ltd
36    Alpha Motors Pvt Ltd
...                    ...
1379  Alpha Motors Pvt Ltd
1409  Alpha Motors Pvt Ltd
1410  Alpha Motors Pvt Ltd
1411  Alpha Motors Pvt Ltd
1412  Alpha Motors Pvt Ltd

[145 rows x 12 columns]

***`Task 6: Find the average SalesCommission% by calculating the SalesCommission% column.`***

SalesCommission% = SalesCommissionPaid / Sales * 100

In [6]:
tyresales['Sales']=tyresales['PerUnitPrice']*tyresales['UnitsSold']
tyresales['SalesCommission%']=tyresales['SalesCommissionPaid']/tyresales['Sales']*100
tyresales['SalesCommission%'].mean()

5.862378385232829

**`Task 7: Take the user Input for Zone and Find the average SalesCommission% of Central Zone.`**

In [7]:
# Take user input for Zone
user_zone = input("Enter the Zone (e.g., Central, West, East, South, North): ")

# Filter the DataFrame based on the user input
df_filtered = tyresales.query('Zone == @user_zone')

# Calculate the average SalesCommission% for the selected Zone
if not df_filtered.empty:
    avg_commission = df_filtered['SalesCommission%'].mean()
    print(f"Average SalesCommission% for {user_zone} Zone: {avg_commission}%")
else:
    print(f"No data available for the {user_zone} Zone.")

Enter the Zone (e.g., Central, West, East, South, North): Central
Average SalesCommission% for Central Zone: 5.872509602190537%

***`Task 8: Sort the file as per Sales Transaction in descending order and show the top five transactions.`***

In [57]:
tyresales.sort_values('Sales',ascending=False)[['OrderID','Sales']].head()

      OrderID     Sales
1064     1065  39581.19
80         81  37478.45
73         74  37295.28
1285     1286  37060.50
524       525  36947.04

***`Task 9: Find the top 5 sales transactions with highest sales amount at top for ProductCategory 'Car'.`***

In [54]:
tyresales.query('ProductCategory=="Car"').sort_values('Sales',ascending=False)[["OrderID","Sales","ProductCategory"]].head()

      OrderID     Sales ProductCategory
264       265  18443.60             Car
30         31  17690.40             Car
1254     1255  17299.95             Car
1234     1235  17039.00             Car
18         19  16421.08             Car

***`Task 10: Find the Name of top 5 'CustomerNameClean' on basis of amount in a single sales transaction in the month of June.`***

In [10]:
tyresales.query('Month=="June"').sort_values('Sales',ascending=False)[["CustomerNameClean","Sales"]].head()

           CustomerNameClean     Sales
1285  JulietAutomotivePvtLtd  37060.50
1282          HotelWheelsInc  34762.47
1283            IndiaTyresCo  32399.64
1320            IndiaTyresCo  32225.04
1312        GolfMotorCompany  28507.08

***`Task 11: Take the user Input for Zone. Show the total sales of the Zone which is being input by the user.`***                                            
Put the Zone input - West.

In [13]:
# Take user input for Zone
user_input = input("Enter the Zone (e.g., Central, West, East, South, North): ")

# Filter the DataFrame based on the user input
filtered = tyresales.query('Zone == @user_input')

# Calculate the Total Sales for the selected Zone
if not filtered.empty:
    Total_Sales= filtered['Sales'].sum()
    print(f"Total_Sales for {user_zone} Zone: {Total_Sales}")
else:
    print(f"No data available for the {user_zone} Zone.")

Enter the Zone (e.g., Central, West, East, South, North): West
Total_Sales for North Zone: 2565909.16

***`Task 12: List all the sales transactions where PerUnitPrice is more than 398 in descending order based on sales.`***

In [51]:
tyresales.query('PerUnitPrice>398').sort_values('Sales',ascending=False)[["OrderID", "Sales"]]

      OrderID     Sales
1064     1065  39581.19
1285     1286  37060.50
343       344  19914.50
809       810  13199.34

***`Task 13: Find the average SalesCommission% of ProductCategory 'Truck'.`***

In [17]:
tyresales.query('ProductCategory=="Truck"')["SalesCommission%"].mean()

6.502232102980405

***`Task 14: Find the average SalesCommission% of ProductCategory 'Two-wheeler'.`***

In [18]:
tyresales.query('ProductCategory=="Two-wheeler"')["SalesCommission%"].mean()

5.507832631622494

***`Task 15: Find the Maximum Sales of 'Medium' CustomerCategory.`***

In [21]:
tyresales.query('CustomerCategory=="Medium"')["Sales"].max()

39581.19

***`Task 16: Take the user Input for ProductName. Find the Maximum UnitsSold for the specified ProductName.`***

In [23]:
# Take user input for ProductName
ProductName_input = input("Enter the ProductName: ")

# Filter the DataFrame based on the user input
filtered = tyresales.query(' ProductName== @ProductName_input')

# Calculate the UnitsSold for the selected ProductName
if not filtered.empty:
    Max_UnitsSold= filtered['UnitsSold'].max()
    print(f"UnitsSold for {ProductName_input} ProductName: {Max_UnitsSold}")
else:
    print(f"No data available for the {ProductName_input} ProductName.")

Enter the ProductName: Truck Tyres LongHaul
UnitsSold for Truck Tyres LongHaul ProductName: 100

In [24]:
tyresales.query('ProductName=="Truck Tyres LongHaul"')["UnitsSold"].max()

100

**`Task 17: Take the user Input for Month. Find the Average SalesCommission% for the specified Month.`**
Enter the Month input - 'May'

In [29]:
# Take user input for Month
Month_input = input("Enter the Month: ")

# Filter the DataFrame based on the user input
filtered = tyresales.query(' Month== @Month_input')

# Calculate the SalesCommission% for the selected ProductName
if not filtered.empty:
    Avg= filtered['SalesCommission%'].mean()
    print(f"Avg_SalesCommission% for {Month_input} Month: {Avg}")
else:
    print(f"No data available for the {Month_input} Month")

Enter the Month: May
Avg_SalesCommission% for May Month: 5.832810631043766

***`Task 18: Find the total number of transactions`***

In [32]:
tyresales['OrderID'].nunique()   #nunique() method count only unique row, means d't count duplicate rows

1436

In [35]:
tyresales['OrderID'].count()   #count() method count the duplicate row allso

1436

***`Task 19: Take the user input for Product Category. Find the minimum sales commission paid for the specified product category. Enter ProductCategory- Truck`***

In [37]:
# Take user input for Product Category
ProductCategory_input = input("Enter the Product Category: ")

# Filter the DataFrame based on the user input
filtered = tyresales.query(' ProductCategory== @ProductCategory_input')

# Calculate the SalesCommission% for the selected ProductName
if not filtered.empty:
    min= filtered['SalesCommissionPaid'].min()
    print(f"min_SalesCommissionPaid for {ProductCategory_input} ProductCategory: {min}")
else:
    print(f"No data available for the {ProductCategory_input} ProductCategory")

Enter the Product Category: Truck
min_SalesCommissionPaid for Truck ProductCategory: 144.08

In [38]:
tyresales.query('ProductCategory=="Truck"')["SalesCommissionPaid"].min()  #---comparison with out user input

144.08

***`Task 20: Find the average per unit price of the north zone.`***

In [39]:
tyresales.query('Zone=="North"')["PerUnitPrice"].mean()

159.60303571428574

***`Task 21: Take a user input for Month. Find the number of transactions (OrderID) in the particular month. Take Month- April.`***

In [41]:
# Take user input for Month
Month_input = input("Enter the Month: ")

# Filter the DataFrame based on the user input
filtered = tyresales.query(' Month== @Month_input')

# Calculate the SalesCommission% for the selected ProductName
if not filtered.empty:
   Num_transaction = filtered['OrderID'].count()
   print(f"Num_transaction for {Month_input} Month: {Num_transaction}")
else:
   print(f"No data available for the {Month_input} Month")

Enter the Month: April
Num_transaction for April Month: 245

In [42]:
tyresales.query('Month=="April"')["OrderID"].count()

245

***`Task 22: Find the average sales of all transactions where Units sold is 99.`***

In [43]:
tyresales.query('UnitsSold==99')["Sales"].mean()

18956.52

***`Task 23: Show the top 5 transactions showing lowest Units sold on the top for product category Car.`***

In [50]:
tyresales.query('ProductCategory=="Car"').sort_values('UnitsSold',ascending=True)[["OrderID","UnitsSold"]].head()

      OrderID  UnitsSold
1222     1223         10
1012     1013         10
268       269         10
479       480         10
511       512         11