# UrbanHome Furnishings Sales Analysis

You have been provided with the sales dataset for UrbanHome Furnishings. The company primarily sells its products to commercial clients in four cities. There are three salespersons who work across multiple cities. The management wants to derive insights from the sales data for April, May, and June. For this you are asked by the management to complete the following tasks.

**Task 1:**

Import Pandas Library and create a dataframe named "sales‚Äù from a given URL and then print it.

URL -
https://raw.githubusercontent.com/Invact-Abhay/DOE11/main/DOE10CW%20-%20Sheet1.csv

In [1]:
import pandas as pd
sales=pd.read_csv(" https://raw.githubusercontent.com/Invact-Abhay/DOE11/main/DOE10CW%20-%20Sheet1.csv")
sales

    Order #  Year  Month   Product   Salesperson     City    Sales  Unit
0         1  2024  April   TV unit    Amit Kumar     Pune  36409.0   451
1         2  2024    May       Bed  Vipin Sharma   Mumbai  53961.5   317
2         3  2024   June      Sofa       Praveen     Pune  27270.0   595
3         4  2024  April  Cupboard    Amit Kumar  Kolkata  43299.5   320
4         5  2024    May   TV unit  Vipin Sharma  Kolkata  67966.0   443
5         6  2024   June       Bed       Praveen     Pune  46807.0   663
6         7  2024  April      Sofa  Vipin Sharma  Chennai  22732.0   507
7         8  2024    May  Cupboard  Vipin Sharma   Mumbai  55569.0   366
8         9  2024   June   TV unit  Vipin Sharma     Pune  43745.0   306
9        10  2024  April       Bed    Amit Kumar  Chennai  65311.0   634
10       11  2024    May      Sofa    Amit Kumar  Chennai  62340.0   389
11       12  2024   June  Cupboard       Praveen  Kolkata  57309.0   563
12       13  2024  April   TV unit  Vipin Sharma  Chennai  46449.5   502
13       14  2024    May       Bed  Vipin Sharma   Mumbai  17315.0   540
14       15  2024   June      Sofa       Praveen     Pune  25947.0   577
15       16  2024  April  Cupboard  Vipin Sharma  Chennai  18147.0   451
16       17  2024    May   TV unit       Praveen  Kolkata  68396.0   661
17       18  2024   June       Bed  Vipin Sharma   Mumbai  44702.0   423
18       19  2024  April      Sofa    Amit Kumar     Pune  25085.0   440
19       20  2024    May  Cupboard       Praveen  Chennai  11222.0   306
20       21  2024   June   TV unit  Vipin Sharma   Mumbai  69936.0   422
21       22  2024  April       Bed       Praveen  Chennai  55332.5   553
22       23  2024    May      Sofa  Vipin Sharma     Pune  66446.0   453
23       24  2024   June  Cupboard       Praveen  Kolkata  56260.0   671
24       25  2024  April   TV unit       Praveen  Chennai  35349.0   325
25       26  2024    May       Bed       Praveen  Kolkata  66327.5   605
26       27  2024   June      Sofa       Praveen   Mumbai  43085.5   371
27       28  2024   June  Cupboard    Amit Kumar  Chennai  36084.0   498
28       29  2024    May   TV unit  Vipin Sharma     Pune  40728.0   666
29       30  2024   June       Bed       Praveen   Mumbai  44702.0   577
30       31  2024  April       Bed  Vipin Sharma   Mumbai  25085.0   451
31       32  2024   June      Sofa       Praveen  Chennai  11222.0   661
32       33  2024   June  Cupboard    Amit Kumar     Pune  44702.0   227
33       34  2024  April   TV unit  Vipin Sharma   Mumbai  25085.0   642
34       35  2024    May  Cupboard       Praveen  Kolkata  15612.0   354


**Task 2:**

Sort the sales dataframe by arranging

"City‚Äù column in descending order

then ‚ÄúSalesperson‚Äù column in ascending order

In [5]:
sales.sort_values(["City","Salesperson"],ascending=[False,True])

    Order #  Year  Month   Product   Salesperson     City    Sales  Unit
0         1  2024  April   TV unit    Amit Kumar     Pune  36409.0   451
18       19  2024  April      Sofa    Amit Kumar     Pune  25085.0   440
32       33  2024   June  Cupboard    Amit Kumar     Pune  44702.0   227
2         3  2024   June      Sofa       Praveen     Pune  27270.0   595
5         6  2024   June       Bed       Praveen     Pune  46807.0   663
14       15  2024   June      Sofa       Praveen     Pune  25947.0   577
8         9  2024   June   TV unit  Vipin Sharma     Pune  43745.0   306
22       23  2024    May      Sofa  Vipin Sharma     Pune  66446.0   453
28       29  2024    May   TV unit  Vipin Sharma     Pune  40728.0   666
26       27  2024   June      Sofa       Praveen   Mumbai  43085.5   371
29       30  2024   June       Bed       Praveen   Mumbai  44702.0   577
1         2  2024    May       Bed  Vipin Sharma   Mumbai  53961.5   317
7         8  2024    May  Cupboard  Vipin Sharma   Mumbai  55569.0   366
13       14  2024    May       Bed  Vipin Sharma   Mumbai  17315.0   540
17       18  2024   June       Bed  Vipin Sharma   Mumbai  44702.0   423
20       21  2024   June   TV unit  Vipin Sharma   Mumbai  69936.0   422
30       31  2024  April       Bed  Vipin Sharma   Mumbai  25085.0   451
33       34  2024  April   TV unit  Vipin Sharma   Mumbai  25085.0   642
3         4  2024  April  Cupboard    Amit Kumar  Kolkata  43299.5   320
11       12  2024   June  Cupboard       Praveen  Kolkata  57309.0   563
16       17  2024    May   TV unit       Praveen  Kolkata  68396.0   661
23       24  2024   June  Cupboard       Praveen  Kolkata  56260.0   671
25       26  2024    May       Bed       Praveen  Kolkata  66327.5   605
34       35  2024    May  Cupboard       Praveen  Kolkata  15612.0   354
4         5  2024    May   TV unit  Vipin Sharma  Kolkata  67966.0   443
9        10  2024  April       Bed    Amit Kumar  Chennai  65311.0   634
10       11  2024    May      Sofa    Amit Kumar  Chennai  62340.0   389
27       28  2024   June  Cupboard    Amit Kumar  Chennai  36084.0   498
19       20  2024    May  Cupboard       Praveen  Chennai  11222.0   306
21       22  2024  April       Bed       Praveen  Chennai  55332.5   553
24       25  2024  April   TV unit       Praveen  Chennai  35349.0   325
31       32  2024   June      Sofa       Praveen  Chennai  11222.0   661
6         7  2024  April      Sofa  Vipin Sharma  Chennai  22732.0   507
12       13  2024  April   TV unit  Vipin Sharma  Chennai  46449.5   502
15       16  2024  April  Cupboard  Vipin Sharma  Chennai  18147.0   451

**Task 3:**

Sort the sales dataframe by arranging

"Salesperson‚Äù column in ascending order

then ‚ÄúSales‚Äù column in ascending order

In [6]:
sales.sort_values(["Salesperson","Sales"],ascending=[True,True])

    Order #  Year  Month   Product   Salesperson     City    Sales  Unit
18       19  2024  April      Sofa    Amit Kumar     Pune  25085.0   440
27       28  2024   June  Cupboard    Amit Kumar  Chennai  36084.0   498
0         1  2024  April   TV unit    Amit Kumar     Pune  36409.0   451
3         4  2024  April  Cupboard    Amit Kumar  Kolkata  43299.5   320
32       33  2024   June  Cupboard    Amit Kumar     Pune  44702.0   227
10       11  2024    May      Sofa    Amit Kumar  Chennai  62340.0   389
9        10  2024  April       Bed    Amit Kumar  Chennai  65311.0   634
19       20  2024    May  Cupboard       Praveen  Chennai  11222.0   306
31       32  2024   June      Sofa       Praveen  Chennai  11222.0   661
34       35  2024    May  Cupboard       Praveen  Kolkata  15612.0   354
14       15  2024   June      Sofa       Praveen     Pune  25947.0   577
2         3  2024   June      Sofa       Praveen     Pune  27270.0   595
24       25  2024  April   TV unit       Praveen  Chennai  35349.0   325
26       27  2024   June      Sofa       Praveen   Mumbai  43085.5   371
29       30  2024   June       Bed       Praveen   Mumbai  44702.0   577
5         6  2024   June       Bed       Praveen     Pune  46807.0   663
21       22  2024  April       Bed       Praveen  Chennai  55332.5   553
23       24  2024   June  Cupboard       Praveen  Kolkata  56260.0   671
11       12  2024   June  Cupboard       Praveen  Kolkata  57309.0   563
25       26  2024    May       Bed       Praveen  Kolkata  66327.5   605
16       17  2024    May   TV unit       Praveen  Kolkata  68396.0   661
13       14  2024    May       Bed  Vipin Sharma   Mumbai  17315.0   540
15       16  2024  April  Cupboard  Vipin Sharma  Chennai  18147.0   451
6         7  2024  April      Sofa  Vipin Sharma  Chennai  22732.0   507
30       31  2024  April       Bed  Vipin Sharma   Mumbai  25085.0   451
33       34  2024  April   TV unit  Vipin Sharma   Mumbai  25085.0   642
28       29  2024    May   TV unit  Vipin Sharma     Pune  40728.0   666
8         9  2024   June   TV unit  Vipin Sharma     Pune  43745.0   306
17       18  2024   June       Bed  Vipin Sharma   Mumbai  44702.0   423
12       13  2024  April   TV unit  Vipin Sharma  Chennai  46449.5   502
1         2  2024    May       Bed  Vipin Sharma   Mumbai  53961.5   317
7         8  2024    May  Cupboard  Vipin Sharma   Mumbai  55569.0   366
22       23  2024    May      Sofa  Vipin Sharma     Pune  66446.0   453
4         5  2024    May   TV unit  Vipin Sharma  Kolkata  67966.0   443
20       21  2024   June   TV unit  Vipin Sharma   Mumbai  69936.0   422

**Task 4:**

Filter the sales dataframe for

Salesperson - "Vipin Sharma" and "Amit Kumar"

Sort the Data Table by arranging

"Salesperson‚Äù column in ascending order

then ‚ÄúSales‚Äù column in descending order

In [7]:
sales.query('Salesperson in ["Vipin Sharma","Amit Kumar"]').sort_values(["Salesperson","Sales"],ascending=[True,False])

    Order #  Year  Month   Product   Salesperson     City    Sales  Unit
9        10  2024  April       Bed    Amit Kumar  Chennai  65311.0   634
10       11  2024    May      Sofa    Amit Kumar  Chennai  62340.0   389
32       33  2024   June  Cupboard    Amit Kumar     Pune  44702.0   227
3         4  2024  April  Cupboard    Amit Kumar  Kolkata  43299.5   320
0         1  2024  April   TV unit    Amit Kumar     Pune  36409.0   451
27       28  2024   June  Cupboard    Amit Kumar  Chennai  36084.0   498
18       19  2024  April      Sofa    Amit Kumar     Pune  25085.0   440
20       21  2024   June   TV unit  Vipin Sharma   Mumbai  69936.0   422
4         5  2024    May   TV unit  Vipin Sharma  Kolkata  67966.0   443
22       23  2024    May      Sofa  Vipin Sharma     Pune  66446.0   453
7         8  2024    May  Cupboard  Vipin Sharma   Mumbai  55569.0   366
1         2  2024    May       Bed  Vipin Sharma   Mumbai  53961.5   317
12       13  2024  April   TV unit  Vipin Sharma  Chennai  46449.5   502
17       18  2024   June       Bed  Vipin Sharma   Mumbai  44702.0   423
8         9  2024   June   TV unit  Vipin Sharma     Pune  43745.0   306
28       29  2024    May   TV unit  Vipin Sharma     Pune  40728.0   666
30       31  2024  April       Bed  Vipin Sharma   Mumbai  25085.0   451
33       34  2024  April   TV unit  Vipin Sharma   Mumbai  25085.0   642
6         7  2024  April      Sofa  Vipin Sharma  Chennai  22732.0   507
15       16  2024  April  Cupboard  Vipin Sharma  Chennai  18147.0   451
13       14  2024    May       Bed  Vipin Sharma   Mumbai  17315.0   540

**Task 5:**

Filter the sales dataframe for

For the Month - "April"

and Sales less than 26000

In [8]:
sales.query('Month=="April" and Sales<26000')

    Order #  Year  Month   Product   Salesperson     City    Sales  Unit
6         7  2024  April      Sofa  Vipin Sharma  Chennai  22732.0   507
15       16  2024  April  Cupboard  Vipin Sharma  Chennai  18147.0   451
18       19  2024  April      Sofa    Amit Kumar     Pune  25085.0   440
30       31  2024  April       Bed  Vipin Sharma   Mumbai  25085.0   451
33       34  2024  April   TV unit  Vipin Sharma   Mumbai  25085.0   642

**Task 6:**

Filter the sales dataframe for

For the Month - "April"

and Sales less than average sales

In [9]:
sales.query('Month=="April" and Sales<Sales.mean()')

    Order #  Year  Month   Product   Salesperson     City    Sales  Unit
0         1  2024  April   TV unit    Amit Kumar     Pune  36409.0   451
6         7  2024  April      Sofa  Vipin Sharma  Chennai  22732.0   507
15       16  2024  April  Cupboard  Vipin Sharma  Chennai  18147.0   451
18       19  2024  April      Sofa    Amit Kumar     Pune  25085.0   440
24       25  2024  April   TV unit       Praveen  Chennai  35349.0   325
30       31  2024  April       Bed  Vipin Sharma   Mumbai  25085.0   451
33       34  2024  April   TV unit  Vipin Sharma   Mumbai  25085.0   642

**Task 7:**

Filter the sales dataframe for

For the Month - "April"

and Sales less than 25000

Sort the Filtered Data Table by arranging

‚ÄúSales‚Äù column in descending order

In [11]:
sales.query('Month=="April" and Sales<25000').sort_values('Sales',ascending=False)

    Order #  Year  Month   Product   Salesperson     City    Sales  Unit
6         7  2024  April      Sofa  Vipin Sharma  Chennai  22732.0   507
15       16  2024  April  Cupboard  Vipin Sharma  Chennai  18147.0   451

**Task 8:**

Filter the sales dataframe for

For the Month - "June"

and Sales greater than 25000

Sort the Data Table by arranging

‚ÄúSales‚Äù column in ascending order

Retrieve only Sales Column

In [14]:
sales.query('Month=="June" and Sales>25000').sort_values('Sales',ascending=True)["Sales"]

14    25947.0
2     27270.0
27    36084.0
26    43085.5
8     43745.0
17    44702.0
29    44702.0
32    44702.0
5     46807.0
23    56260.0
11    57309.0
20    69936.0
Name: Sales, dtype: float64

**Task 9:**

Filter the sales dataframe for

For the Month - "June"

and Sales less than Average Sales

Sort the Data Table by arranging

‚ÄúSales‚Äù column in descending order

Retrieve ‚ÄòSalesperson‚Äô Column

In [15]:
sales.query('Month=="June" and Sales<Sales.mean()').sort_values('Sales',ascending=False)["Salesperson"]

27    Amit Kumar
2        Praveen
14       Praveen
31       Praveen
Name: Salesperson, dtype: object

**Task 10:**

Filter the sales dataframe for

City - "Pune" and "Mumbai"

Month - "April"

Sales greater than 25000

Sort the Filtered Data Table by arranging

"City‚Äù column in descending order

then ‚ÄúSalesperson‚Äù column in ascending order

Retrieve ‚ÄòSalesperson‚Äô Column

In [19]:
sales.query('City in ["Pune","Mumbai"] and Month=="April" and Sales>25000').sort_values(["City","Salesperson"],ascending=[False,True])["Salesperson"]

0       Amit Kumar
18      Amit Kumar
30    Vipin Sharma
33    Vipin Sharma
Name: Salesperson, dtype: object

**Task 11:**

Store the user input for the month in the variable named as "Input_Month". Text to be shown to the user: "Enter the Month Name : "

Filter the sales dataframe for

City - "Pune" and "Mumbai" and Month - 'To be taken from user input' and store the resultant data in "Sales1" dataframe.

Print the Sales1 dataframe

At the end the user input should be-

Month (Input_Month) - Enter the Month Name :  'April'

In [20]:
Input_Month=input("Enter the Month Name : ")
Sales1=sales.query('City in ["Pune","Mumbai"] and Month==@Input_Month')
Sales1

Enter the Month Name : April

    Order #  Year  Month  Product   Salesperson    City    Sales  Unit
0         1  2024  April  TV unit    Amit Kumar    Pune  36409.0   451
18       19  2024  April     Sofa    Amit Kumar    Pune  25085.0   440
30       31  2024  April      Bed  Vipin Sharma  Mumbai  25085.0   451
33       34  2024  April  TV unit  Vipin Sharma  Mumbai  25085.0   642

**Task 12:**

Store the user input for the city in the variable named as "Input_City". Text to be shown to the user "Enter the City Name : "

Filter the sales dataframe for

Month- "April" and "May"

and Sales greater than 50000

and City to be taken from user input. Store the resultant data in "Sales2" dataframe.

Sort the "Sales2" dataframe by arranging

‚ÄúUnit‚Äù column in descending order

At the end the user input should be-

City (Input_City) - Enter the name of city: 'Chennai'

In [24]:
Input_City=input("Enter the City Name : ")
Sales2=sales.query('Month in ["April","May"] and Sales>50000 and City==@Input_City')
Sales2.sort_values('Unit',ascending=False)

Enter the City Name : Chennai

    Order #  Year  Month Product Salesperson     City    Sales  Unit
9        10  2024  April     Bed  Amit Kumar  Chennai  65311.0   634
21       22  2024  April     Bed     Praveen  Chennai  55332.5   553
10       11  2024    May    Sofa  Amit Kumar  Chennai  62340.0   389

**Task 13:**

Store the user input for the city in the variable named as "Input_City1". Text to be shown to the user "Enter the City Name : "

Store the user input for the product in the variable named as "Input_Product". Text to be shown to the user "Enter the Product Name : "

Filter the sales dataframe for
City to be taken from user input
and Product to be taken from user input. Store the resultant data in "Sales3" dataframe.

Sort the "Sales3" by arranging

"Sales‚Äù column in descending order

At the end the user input should be-

City (Input_City1) - Enter the name of city: Pune

Product (Input_Product) - Enter the name of product: Sofa

In [27]:
Input_City1=input("Enter the City Name : ")
Input_Product=input("Enter the Product Name : ")
Sales3=sales.query('City==@Input_City1 and Product==@Input_Product')
Sales3.sort_values('Sales',ascending=False)

Enter the City Name : Pune
Enter the Product Name : Sofa

    Order #  Year  Month Product   Salesperson  City    Sales  Unit
22       23  2024    May    Sofa  Vipin Sharma  Pune  66446.0   453
2         3  2024   June    Sofa       Praveen  Pune  27270.0   595
14       15  2024   June    Sofa       Praveen  Pune  25947.0   577
18       19  2024  April    Sofa    Amit Kumar  Pune  25085.0   440

**Task 14:**

Store the user input for the city in the variable named as "Input_City3". Text to be shown to the user "Enter the City Name : "

Store the user input for the Salesperson in the variable named as "Input_Salesperson1". Text to be shown to the user "Enter the Salesperson Name : "
Filter the sales dataframe for
City to be taken from user input
and Salesperson to be taken from user input. Store the resultant data in "Sales4" dataframe.


Create a pivot table using the Sales4 dataframe named pivot_2 to show the Product-wise total sales and total unit for the Salesperson. Use index as Product, columns as Salesperson and values as Sales and Unit. Print this pivot table. This will show the data for the salesperson and city selected by the user.

At the end the user input should be-

City (Input_City3) - Enter the city name : Chennai

Salesperson (Input_Salesperson1) - Enter the Salesperson name : Vipin Sharma

In [31]:
Input_City3=input("Enter the City Name : ")
Input_Salesperson1=input("Enter the Salesperson Name : " )
Sales4=sales.query('City==@Input_City3 and Salesperson==@Input_Salesperson1')
pivot_2=pd.pivot_table(Sales4,index=["Product"],columns=["Salesperson"],values=["Sales","Unit"],aggfunc={"Sales":["sum"],"Unit":["sum"]})
pivot_2

Enter the City Name : Chennai
Enter the Salesperson Name : Vipin Sharma

                   Sales         Unit
                     sum          sum
Salesperson Vipin Sharma Vipin Sharma
Product
Cupboard         18147.0          451
Sofa             22732.0          507
TV unit          46449.5          502

**Submission of exercise:**




*   Once you have completed all the tasks in the colab file, please provide editor‚Äôs access so that evaluators can provide comments if necessary.
*   Once done, copy the link of the colab file and paste it in the box given below. Click on the Submit button to submit your exercise.