# IndianCricketPlayers_PerformanceAnalysis_4.1

***`Task 1: Import the pandas library `***

In [2]:
import pandas as pd

***`Task 2: Create a dataframe named “splr” from a given URL.`***

https://raw.githubusercontent.com/Invact-Abhay/DOE/main/hw2.csv

In [3]:
splr=pd.read_csv("https://raw.githubusercontent.com/Invact-Abhay/DOE/main/hw2.csv")
splr

,PlayerName,Team,State,MatchesPlayed,RunsScored,BattingAverage,HighestScore
0,Aarav Kapoor,MUM,Maharashtra,260,13500,58.92,271
1,Diya Patel,AMD,Gujarat,130,7000,60.84,245
2,Ishan Sharma,CHE,Tamil Nadu,150,8200,47.25,260
3,Riya Gupta,BLR,Karnataka,100,5600,51.38,249
4,Kabir Singh,TVM,Kerala,90,4000,44.20,188
5,Zara Khan,LKO,Uttar Pradesh,220,12000,48.93,272
6,Ananya Reddy,DEL,Delhi,160,8500,47.98,345
7,Arjun Malhotra,HYD,Telangana,110,6000,38.76,189
8,Niharika Sharma,JAI,Rajasthan,100,4200,41.85,178
9,Vikram Chauhan,CHD,Punjab,80,2800,35.37,265
10,Meera Joshi,KOL,West Bengal,260,12000,58.92,267
11,Yuvraj Singh,BHO,Madhya Pradesh,260,12000,60.84,245
12,Aanya Khanna,BBS,Odisha,130,12000,58.92,267
13,Advik Patel,CHD,Haryana,150,13500,60.84,245
14,Rahul Patel,JHA,Jharkhand,179,12500,60.84,299

***`Task 3: Sort the data according to the State in the alphabetical order.`***

In [4]:
splr.sort_values('State',ascending=True)

,PlayerName,Team,State,MatchesPlayed,RunsScored,BattingAverage,HighestScore
6,Ananya Reddy,DEL,Delhi,160,8500,47.98,345
1,Diya Patel,AMD,Gujarat,130,7000,60.84,245
13,Advik Patel,CHD,Haryana,150,13500,60.84,245
14,Rahul Patel,JHA,Jharkhand,179,12500,60.84,299
3,Riya Gupta,BLR,Karnataka,100,5600,51.38,249
4,Kabir Singh,TVM,Kerala,90,4000,44.20,188
11,Yuvraj Singh,BHO,Madhya Pradesh,260,12000,60.84,245
0,Aarav Kapoor,MUM,Maharashtra,260,13500,58.92,271
12,Aanya Khanna,BBS,Odisha,130,12000,58.92,267
9,Vikram Chauhan,CHD,Punjab,80,2800,35.37,265
8,Niharika Sharma,JAI,Rajasthan,100,4200,41.85,178
2,Ishan Sharma,CHE,Tamil Nadu,150,8200,47.25,260
7,Arjun Malhotra,HYD,Telangana,110,6000,38.76,189
5,Zara Khan,LKO,Uttar Pradesh,220,12000,48.93,272
10,Meera Joshi,KOL,West Bengal,260,12000,58.92,267

***`Task 4: Sort the data according to the Team's name in the descending alphabetical order.`***

In [6]:
splr.sort_values('Team',ascending=False)

,PlayerName,Team,State,MatchesPlayed,RunsScored,BattingAverage,HighestScore
4,Kabir Singh,TVM,Kerala,90,4000,44.20,188
0,Aarav Kapoor,MUM,Maharashtra,260,13500,58.92,271
5,Zara Khan,LKO,Uttar Pradesh,220,12000,48.93,272
10,Meera Joshi,KOL,West Bengal,260,12000,58.92,267
14,Rahul Patel,JHA,Jharkhand,179,12500,60.84,299
8,Niharika Sharma,JAI,Rajasthan,100,4200,41.85,178
7,Arjun Malhotra,HYD,Telangana,110,6000,38.76,189
6,Ananya Reddy,DEL,Delhi,160,8500,47.98,345
2,Ishan Sharma,CHE,Tamil Nadu,150,8200,47.25,260
9,Vikram Chauhan,CHD,Punjab,80,2800,35.37,265
13,Advik Patel,CHD,Haryana,150,13500,60.84,245
3,Riya Gupta,BLR,Karnataka,100,5600,51.38,249
11,Yuvraj Singh,BHO,Madhya Pradesh,260,12000,60.84,245
12,Aanya Khanna,BBS,Odisha,130,12000,58.92,267
1,Diya Patel,AMD,Gujarat,130,7000,60.84,245

***`Task 5: Sort the data according to the Total Matches played in the ascending order.`***

In [7]:
splr.sort_values('MatchesPlayed',ascending=True)

,PlayerName,Team,State,MatchesPlayed,RunsScored,BattingAverage,HighestScore
9,Vikram Chauhan,CHD,Punjab,80,2800,35.37,265
4,Kabir Singh,TVM,Kerala,90,4000,44.20,188
3,Riya Gupta,BLR,Karnataka,100,5600,51.38,249
8,Niharika Sharma,JAI,Rajasthan,100,4200,41.85,178
7,Arjun Malhotra,HYD,Telangana,110,6000,38.76,189
1,Diya Patel,AMD,Gujarat,130,7000,60.84,245
12,Aanya Khanna,BBS,Odisha,130,12000,58.92,267
2,Ishan Sharma,CHE,Tamil Nadu,150,8200,47.25,260
13,Advik Patel,CHD,Haryana,150,13500,60.84,245
6,Ananya Reddy,DEL,Delhi,160,8500,47.98,345
14,Rahul Patel,JHA,Jharkhand,179,12500,60.84,299
5,Zara Khan,LKO,Uttar Pradesh,220,12000,48.93,272
0,Aarav Kapoor,MUM,Maharashtra,260,13500,58.92,271
10,Meera Joshi,KOL,West Bengal,260,12000,58.92,267
11,Yuvraj Singh,BHO,Madhya Pradesh,260,12000,60.84,245

***`Task 6: Sort the data according to the Total Matches played in the descending order.`***

In [8]:
splr.sort_values('MatchesPlayed',ascending=False)

,PlayerName,Team,State,MatchesPlayed,RunsScored,BattingAverage,HighestScore
0,Aarav Kapoor,MUM,Maharashtra,260,13500,58.92,271
10,Meera Joshi,KOL,West Bengal,260,12000,58.92,267
11,Yuvraj Singh,BHO,Madhya Pradesh,260,12000,60.84,245
5,Zara Khan,LKO,Uttar Pradesh,220,12000,48.93,272
14,Rahul Patel,JHA,Jharkhand,179,12500,60.84,299
6,Ananya Reddy,DEL,Delhi,160,8500,47.98,345
2,Ishan Sharma,CHE,Tamil Nadu,150,8200,47.25,260
13,Advik Patel,CHD,Haryana,150,13500,60.84,245
1,Diya Patel,AMD,Gujarat,130,7000,60.84,245
12,Aanya Khanna,BBS,Odisha,130,12000,58.92,267
7,Arjun Malhotra,HYD,Telangana,110,6000,38.76,189
3,Riya Gupta,BLR,Karnataka,100,5600,51.38,249
8,Niharika Sharma,JAI,Rajasthan,100,4200,41.85,178
4,Kabir Singh,TVM,Kerala,90,4000,44.20,188
9,Vikram Chauhan,CHD,Punjab,80,2800,35.37,265

***`Task 7: Sort the data according to the Player's name in the descending alphabetical order and only show the Player's name.`***

In [10]:
splr.sort_values('PlayerName',ascending=False)["PlayerName"]

5           Zara Khan
11       Yuvraj Singh
9      Vikram Chauhan
3          Riya Gupta
14        Rahul Patel
8     Niharika Sharma
10        Meera Joshi
4         Kabir Singh
2        Ishan Sharma
1          Diya Patel
7      Arjun Malhotra
6        Ananya Reddy
13        Advik Patel
0        Aarav Kapoor
12       Aanya Khanna
Name: PlayerName, dtype: object

***`Task 8: Sort the data based on the HighestScore in ascending order and give only the name of the teams of the sorted data.`***

In [12]:
splr.sort_values('HighestScore',ascending=True)["Team"]

8     JAI
4     TVM
7     HYD
1     AMD
11    BHO
13    CHD
3     BLR
2     CHE
9     CHD
10    KOL
12    BBS
0     MUM
5     LKO
14    JHA
6     DEL
Name: Team, dtype: object

***`Task 9: Find the data of the teams who have played less than 100 matches and sort the result on the basis of Team Name in alphabetical order.`***

In [13]:
splr.query('MatchesPlayed<100').sort_values('Team',ascending=True)

,PlayerName,Team,State,MatchesPlayed,RunsScored,BattingAverage,HighestScore
9,Vikram Chauhan,CHD,Punjab,80,2800,35.37,265
4,Kabir Singh,TVM,Kerala,90,4000,44.20,188

***`Task 10: Find the data of the teams who have BattingAverage of 58.92 and sort the result on the basis of Team's name in the descending alphabetical order.`***

In [14]:
splr.query('BattingAverage==58.92').sort_values('Team',ascending=False)

,PlayerName,Team,State,MatchesPlayed,RunsScored,BattingAverage,HighestScore
0,Aarav Kapoor,MUM,Maharashtra,260,13500,58.92,271
10,Meera Joshi,KOL,West Bengal,260,12000,58.92,267
12,Aanya Khanna,BBS,Odisha,130,12000,58.92,267

***`Task 11: Find the data of the teams with HighestScore more than 260 and then sort the data on the Matchesplayed in descending order.`***

In [15]:
splr.query('	HighestScore>260').sort_values('MatchesPlayed',ascending=False)

,PlayerName,Team,State,MatchesPlayed,RunsScored,BattingAverage,HighestScore
0,Aarav Kapoor,MUM,Maharashtra,260,13500,58.92,271
10,Meera Joshi,KOL,West Bengal,260,12000,58.92,267
5,Zara Khan,LKO,Uttar Pradesh,220,12000,48.93,272
14,Rahul Patel,JHA,Jharkhand,179,12500,60.84,299
6,Ananya Reddy,DEL,Delhi,160,8500,47.98,345
12,Aanya Khanna,BBS,Odisha,130,12000,58.92,267
9,Vikram Chauhan,CHD,Punjab,80,2800,35.37,265

***`Task 12: Find the data of the teams that have RunsScored  more than 10000 and then sort the data on the HighestScore in descending order. Get only the Player names for the same.`***

In [16]:
splr.query('RunsScored>10000').sort_values('HighestScore',ascending=False)["PlayerName"]

14     Rahul Patel
5        Zara Khan
0     Aarav Kapoor
10     Meera Joshi
12    Aanya Khanna
11    Yuvraj Singh
13     Advik Patel
Name: PlayerName, dtype: object

***`Task 13: Find the name of the teams whose RunsScored is less than the Average RunsScored of all the teams and then sort the data according to the Player’s name in the alphabetical order. `***

In [17]:
splr.query('RunsScored<RunsScored.mean()').sort_values('PlayerName',ascending=True)

,PlayerName,Team,State,MatchesPlayed,RunsScored,BattingAverage,HighestScore
6,Ananya Reddy,DEL,Delhi,160,8500,47.98,345
7,Arjun Malhotra,HYD,Telangana,110,6000,38.76,189
1,Diya Patel,AMD,Gujarat,130,7000,60.84,245
2,Ishan Sharma,CHE,Tamil Nadu,150,8200,47.25,260
4,Kabir Singh,TVM,Kerala,90,4000,44.20,188
8,Niharika Sharma,JAI,Rajasthan,100,4200,41.85,178
3,Riya Gupta,BLR,Karnataka,100,5600,51.38,249
9,Vikram Chauhan,CHD,Punjab,80,2800,35.37,265

***`Task 14: Find the PlayersName whose MatchesPlayed is less than the average MatchesPlayed and then sort the data according to the PlayersName in descending alphabetical order. Get only the player’s name for the same.`***

In [18]:
splr.query('MatchesPlayed<MatchesPlayed.mean()').sort_values('PlayerName',ascending=False)["PlayerName"]

9      Vikram Chauhan
3          Riya Gupta
8     Niharika Sharma
4         Kabir Singh
2        Ishan Sharma
1          Diya Patel
7      Arjun Malhotra
13        Advik Patel
12       Aanya Khanna
Name: PlayerName, dtype: object

***`Task 15: Find the name of the players whose RunsScored is more than the average RunsScored of all the teams and then sort the data according to the Player’s name in the alphabetical order. Get only the player names for the same.`***

In [19]:
splr.query('RunsScored>RunsScored.mean()').sort_values('PlayerName',ascending=True)["PlayerName"]

12    Aanya Khanna
0     Aarav Kapoor
13     Advik Patel
10     Meera Joshi
14     Rahul Patel
11    Yuvraj Singh
5        Zara Khan
Name: PlayerName, dtype: object